# Generated by Django 5.0.6 on 2024-05-09 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
