# Generated by Django 5.0.6 on 2024-06-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="is_star",
            field=models.BooleanField(default=False),
        ),
    ]
