# Generated by Django 5.0.6 on 2024-05-22 09:10

from django.db import migrations


# DATA MIGRATIONS

def fwds(apps, schema_editor):
    Category = apps.get_model("expenses", "Category")
    Expense = apps.get_model("expenses", "Expense")

    o = Category.objects.create(
        name="Old Expenses",
    )
    Expense.objects.filter(category__isnull=True).update(category=o)


class Migration(migrations.Migration):
    dependencies = [
        ("expenses", "0003_category_expense_category"),
    ]

    operations = [
        migrations.RunPython(fwds),
    ]
